import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "Ar": {
          "1": "اختر اللغة",
          "Welcome": "أهلا بك",
          "Welcome To Araab App": "أهلا بك في العراف",
          "We specialize in reading horoscopes":
              "نحن متخصصون في قراءة الأبراج، والكف والفنجان\n وبطاقات التاروت وأكثر من ذلك",
          "Easy & Safe": "بسهولة و أمان",
          "To reveal what is hidden":
              "لتكشف ما هو مخفي\n تعرف على أسرار حياتك اليومية\n وانظر إلى المستقبل",
          "Discover the secrets of your life": "اكتشف أسرار حياتك",
          "If you are looking for a way":
              "إذا كنت تبحث عن طريقة \nللإجابة على جميع أسئلتك\n تطبيق العراف هو الحل",
          "Sign In": "تسجيل الدخول",
          "Sign in with your E-mail and Password":
              "سجل دخول عن طريق بريدك الالكتروني و كلمة المرور",
          "E-mail": "بريد الالكتروني",
          "Enter Your E-mail": "أدخل بريدك الالكتروني",
          "Password": "كلمة المرور",
          "Enter Your Password": "أدخل كلمة المرور",
          "forgot password?": "نسيت كلمة المرور؟",
          "Sign in": "تسجيل الدخول",
          "Don't have an account?": "لا تملك حساب؟",
          "Sign up": "انشاء حساب",
          "Enter Your User Name": "أدخل اسم الحساب",
          "user name": "اسم الحساب",
          "Enter your Phone Number": "أدخل رقم هاتفك",
          "phone Number": "رقم الهاتف",
          "Enter Your Zodic Sign": "أدخل برجك",
          "Zodiac Sign": "البرج",
          "Sign up with your E-mail and Password":
              "أنشئ حساب عن طريق بريدك الالكتروني و كلمة المرور",
          "have an account?": "تملك حساب؟",
          "Log in": " تسجيل دخول",
          "Continue": "متابعة",
          "Check Email": "تفقد البريد الإلكتروني",
          "Check": "تفقد",
          "please enter your email address to recive a verification code":
              "أدخل بريدك الالكتروني ليصلك كود تحقق",
          "Please Enter The Digit Code That Sent To":
              "رجاء ادخل الرقم الذي تم ارساله الى  ",
          "Re Set Passwor": "إعادة تعيين كلمة المرور",
          "Change Password": "تغيير كلمة المرور",
          "Please Enter Your New Password": "أدخل رجاء كلمة المرور الجديدة",
          "Enter New Password": "أدخل كلمة المرور الجديدة",
          "New Password": "كلمة المرور الجديدة",
          "Re Enter Your New Password": "أعد إدخال كلمة المرور الجديدة",
          "Re New password": "اعادة كلمة المرور",
          "Save": "حفظ",
          "Success": "تم بنجاح",
          "Thank You For Your Time": "شكراً لوقتك",
          "Reset Password Success": "تم تغير كلمة المرور \n بنجاح",
          "Go To Login": "الذهاب لتسجيل الدخول",
          "Verification Code": "كود التحقق من الصحة",
          "Signed Up Successfully": "تم التسجيل \n بنجاح ",
          "Create User": "انشاء حساب",
          "Checking E-mail": "التأكد من البريد الالكتروني",
          "Not Valid Username": "اسم الحساب غير متاح",
          "Not Valid Email": "البريد الالكتروني غير متاح",
          "Not Valid Phone Number": "رقم هاتف غير متاح",
          "please fill the fields": "رجاء املأ الحقول",
          "Can't be less than": "لا يمكن أن تكون أقل من",
          "Can't be larger than": "لا يمكن ان تكون اكثر من",
          "Warning": "تحذير",
          "Do You Want To Close The App": "هل تريد الخروج من التطبيق",
          "Confirm": "تأكيد",
          "Cancel": "الغاء",
          "Email or username already exist":
              "البريد الالكتروني او اسم المستخدمين غير متاح",
          "Verify Code Not Correct": "رقم التحقق غير صحيح",
          "Email or password not correct":
              "كلمة المرور او البريد الالكتروني غير صحيح",
          "Email Not Found": "البريد الالكتروني خاطئ",
          "Password Not Match": "كلمة السر غير متطابقة",
          "Try Again": "حاول مجدداً",
          "search": "بحث",
          "Categories": "القوائم",
          "Top Services For You": "الخدمات الاكثر استخداماً",
          "offer": "عروض",
          "Rating": "تقييم",
          "Home": "الرئيسية",
          "Profile": "الشخصية",
          "Setting": "الاعدادات",
          "Request": "الطلبات",
          "Edit Your Password": "تعديل كلمة السر",
          "Edit": "تعديل",
          "Edit Your Phone Number": "تعديل رقم الهاتف",
          "Edit Your User Name": "تعديل اسم الحساب",
          "Edit Your Zodiac": "تعديل برجك",
          "Add comment": "اضافة تعليق",
          "Write a Comment": "اكتب تعليق",
          "Notification": "اشعارات",
          "Fill your information and your question": "املأ بياناتك و سؤالك",
          "Enter Your Full Name": "أدخل اسمك الكامل",
          "Full Name": "الاسم الكامل",
          "Enter Your Question": "أدخل سؤالك",
          "Question": "السؤال",
          "Choose Image": "اختر صورة",
          "Image Succefuly uploaded": "تم اختيار الصورة",
          "Upload photo From Camera": "من الكاميرا",
          "Upload photo From Gallery": "من الاستديو",
          "Send": "ارسال",
          "please fill all the info": "الرجاء ملأ جميع الحقول",
          "Admin approved": "موافقة الادمن",
          "price": "السعر",
          "Waiting For Answer": "بانتظار الرد",
          "Answer delevierd": "وصول الرد",
          "Answer": "الرد",
          "Add a rating": "اضافة تقييم",
          "Technical Support": "الدعم الفني",
          "Language": "اللغة",
          "Contact Us": "اتصل بنا",
          "Log Out": "تسجيل خروج",
          "Please enter your questions or problems you are having":
              "الرجاء إدخال أسئلتك أو المشاكل التي تواجهها",
          "Contact": "تواصل",
          "Bio": "السيرة الذاتية",
          "Favorite": "المفضلة",
          "Rating Dialog": "تقييم",
          "Tap a star to set your rating": "اضغط على نجمة لتعيين تقييمك",
          "please insert an image": "الرجاء رفع صورة",
          "Your comment will succefulyy add": "سيتم اضافة تعليقك",
          "when admin approved it": "عند موافقة الادمن",
          "Virgo": "العذراء",
          "Libra": "الميزان",
          "Scorpion": "العقرب",
          "Sagittarius": "القوس",
          "Capricorn": "الجدي",
          "Aquarius": "الدلو",
          "Pisces": "الحوت",
          "Aries": "الحمل",
          "Taurus": "الثور",
          "Gemini": "الجوزاء",
          "Cancer": "السرطان",
          "Leo": "الاسد",
          "Done": "تم",
          "Edited Complete": "تم التعديل بنجاح",
          "Pause": "ايقاف",
          "Play": "تشغيل",
          "online": "متصل",
          "offline": "غير متصل",
          "Rejected Request": "الطلبات المرفوضة",
          "Archive": "الأرشيف",
          "Responses": "الاستجابات",
          "Please enter your Credit Card": "الرجاء ادخال رقم بطاقة الائتمان",
          "Add": "إضافة",
          "Explore Your Insight": "اكتشف البصيرة الخاصة بك"
        },
        "En": {
          "1": "Choose Language",
          "Welcome": "Welcome ",
          "Welcome To Araab App": "Welcome To Araab App",
          "We specialize in reading horoscopes":
              "We specialize in reading horoscopes, palms, cups,\n tarot cards, and more",
          "Easy & Safe": "Easy & Safe",
          "To reveal what is hidden":
              "To reveal what is hidden,\n know the secrets of your daily life,\n and see the future",
          "Discover the secrets of your life":
              "Discover the secrets of your life",
          "If you are looking for a way":
              "If you are looking for a way \nto answer all your questions,\n Al-Araaf application is the solution.",
          "Sign In": "Sign In",
          "Sign in with your E-mail and Password":
              "Sign in with your E-mail and Password",
          "E-mail": "E-mail",
          "Enter Your E-mail": "Enter Your E-mail",
          "Password": "Password",
          "Enter Your Password": "Enter Your Password",
          "forgot password?": "forgot password?",
          "Sign in": "Sign in",
          "Don't have an account?": "Don't have an account?",
          "Sign up": "Sign up",
          "Enter Your User Name": "Enter Your User Name",
          "user name": "user name",
          "Enter your Phone Number": "Enter your Phone Number",
          "phone Number": "phone Number",
          "Enter Your Zodic Sign": "Enter Your Zodic Sign",
          "Zodiac Sign": "Zodiac Sign",
          "Sign up with your E-mail and Password":
              "Sign up with your E-mail and Password",
          "have an account?": "have an account?",
          "Log in": "Log in",
          "Continue": "Continue",
          "Check Email": "Check Email",
          "Check": "Check",
          "please enter your email address to recive a verification code":
              "please enter your email address to recive a verification code",
          "Please Enter The Digit Code That Sent To":
              "Please Enter The Digit Code That Sent To  ",
          "Re Set Passwor": "Re Set Password",
          "Change Password": "Change Password",
          "Please Enter Your New Password": "Please Enter Your New Password",
          "Enter New Password": "Enter New Password",
          "New Password": "New Password",
          "Re Enter Your New Password": "Re Enter Your New Password",
          "Re New password": "Re New password",
          "Save": "Save",
          "Success": "Success",
          "Thank You For Your Time": "Thank You For Your Time",
          "Reset Password Success": "Reset Password \nSuccessfully",
          "Go To Login": "Go To Login",
          "Verification Code": "Verification Code",
          "Signed Up Successfully": "Signed Up \nSuccessfully",
          "Create User": "Create User",
          "Checking E-mail": "Checking E-mail",
          "Not Valid Username": "Not Valid Username",
          "Not Valid Email": "Not Valid Email",
          "Not Valid Phone Number": "Not Valid Phone Number",
          "please fill the fields": "please fill the fields",
          "Can't be less than": "Can't be less than",
          "Can't be larger than": "Can't be larger than",
          "Warning": "Warning",
          "Do You Want To Close The App": "Do You Want To Close The App",
          "Confirm": "Confirm",
          "Cancel": "Cancel",
          "Email or username already exist": "Email or username already exist",
          "Verify Code Not Correct": "Verify Code Not Correct",
          "Email or password not correct": "Email or password not correct",
          "Email Not Found": "Email Not Found",
          "Password Not Match": "Password Not Match",
          "Try Again": "Try Again",
          "search": "search",
          "Categories": "Categories",
          "Top Services For You": "Top Services For You",
          "offer": "offer",
          "Rating": "Rating",
          "Home": "Home",
          "Profile": "Profile",
          "Setting": "Setting",
          "Request": "Request",
          "Edit Your Password": "Edit Your Password",
          "Edit": "Edit",
          "Edit Your Phone Number": "Edit Your Phone Number",
          "Edit Your User Name": "Edit Your User Name",
          "Edit Your Zodiac": "Edit Your Zodiac",
          "Add comment": "Add comment",
          "Write a Comment": "Write a Comment ..",
          "Notification": "Notification",
          "Fill your information and your question":
              "Fill your information and your question",
          "Enter Your Full Name": "Enter Your Full Name",
          "Full Name": "Full Name",
          "Enter Your Question": "Enter Your Question",
          "Question": "Question",
          "Choose Image": "Choose Image",
          "Image Succefuly uploaded": "Image Succefuly uploaded",
          "Upload photo From Camera": "Upload photo From Camera",
          "Upload photo From Gallery": "Upload photo From Gallery",
          "Send": "Send",
          "please fill all the info": "please fill all the info",
          "Admin approved": "Admin approved",
          "price": "price",
          "Waiting For Answer": "Waiting For Answer",
          "Answer delevierd": "Answer delevierd",
          "Answer": "Answer",
          "Add a rating": "Add a rating",
          "Technical Support": "Technical Support",
          "Language": "Language",
          "Contact Us": "Contact Us",
          "Log Out": "Log Out",
          "Please enter your questions or problems you are having":
              "Please enter your questions or problems you are having",
          "Contact": "Contact",
          "Bio": "Bio",
          "Favorite": "Favorite",
          "Rating Dialog": "Rating Dialog",
          "Tap a star to set your rating": "Tap a star to set your rating",
          "please insert an image": "please insert an image",
          "Your comment will succefulyy add":
              "Your comment will succefulyy add ",
          "when admin approved it": "when admin approved it",
          "Virgo": "Virgo",
          "Libra": "Libra",
          "Scorpion": "Scorpion",
          "Sagittarius": "Sagittarius",
          "Capricorn": "Capricorn",
          "Aquarius": "Aquarius",
          "Pisces": "Pisces",
          "Aries": "Aries",
          "Taurus": "Taurus",
          "Gemini": "Gemini",
          "Cancer": "Cancer",
          "Leo": "Leo",
          "Done": "Done",
          "Edited Complete": "Edited Complete",
          "Pause": "Pause",
          "Play": "Play",
          "online": "online",
          "offline": "offline",
          "Rejected Request": "Rejected Request",
          "Archive": "Archive",
          "Responses": "Responses",
          "Please enter your Credit Card": "Please enter your Credit Card",
          "Add": "Add",
          "Explore Your Insight": "Explore Your Insight",
        },
        "Fr": {
          "1": "Choisissez la langue",
          "Welcome": "Bienvenue ",
          "Welcome To Araab App": "Bienvenue sur l'application Arab",
          "We specialize in reading horoscopes":
              "Nous sommes spécialisés dans la lecture d'horoscopes, de paumes, de coupes,\n cartes de tarot, et plus encore",
          "Easy & Safe": "Facile & sûr",
          "To reveal what is hidden":
              "Pour révéler ce qui est caché,\n connaître les secrets de votre vie quotidienne,\n et voir l'avenir",
          "Discover the secrets of your life":
              "Discover the secrets of your life",
          "If you are looking for a way":
              "Si vous cherchez un moyen \n pour répondre à toutes vos questions,\n L'application Al-Araaf est la solution.",
          "Sign In": "Se connecter",
          "Sign in with your E-mail and Password":
              "Connectez-vous avec votre e-mail et votre mot de passe",
          "E-mail": "E-mail",
          "Enter Your E-mail": "Entrer votre Email",
          "Password": "Mot de passe",
          "Enter Your Password": "Tapez votre mot de passe",
          "forgot password?": "Mot de passe oublié?",
          "Sign in": "se connecter",
          "Don't have an account?": "Vous n'avez pas de compte ?",
          "Sign up": "S'inscrire",
          "Enter Your User Name": "Entrez votre nom d'utilisateur",
          "user name": "nom d'utilisateur",
          "Enter your Phone Number": "Entrez votre numéro de téléphone",
          "phone Number": "numéro de téléphone",
          "Enter Your Zodic Sign": "Entrez votre signe du zodiaque",
          "Zodiac Sign": "Signe du zodiaque",
          "Sign up with your E-mail and Password":
              "Inscrivez-vous avec votre e-mail et votre mot de passe",
          "have an account?": "avoir un compte?",
          "Log in": "Se connecter",
          "Continue": "Continuer",
          "Check Email": "Vérifier le courriel",
          "Check": "Vérifier",
          "please enter your email address to recive a verification code":
              "veuillez entrer votre adresse e-mail pour recevoir un code de vérification",
          "Please Enter The Digit Code That Sent To":
              "Veuillez entrer le code numérique envoyé à  ",
          "Re Set Passwor": "réinitialiser le mot de passe",
          "Change Password": "Changer le mot de passe",
          "Please Enter Your New Password":
              "Veuillez entrer votre nouveau mot de passe",
          "Enter New Password": "Entrez un nouveau mot de passe",
          "New Password": "nouveau mot de passe",
          "Re Enter Your New Password":
              "Entrez à nouveau votre nouveau mot de passe",
          "Re New password": "Concernant Nouveau mot de passe",
          "Save": "Sauvegarder",
          "Success": "Succès",
          "Thank You For Your Time": "Merci pour votre temps",
          "Reset Password Success":
              "réinitialiser le mot de passe \n Avec succès",
          "Go To Login": "Aller à la connexion",
          "Verification Code": "Le code de vérification",
          "Signed Up Successfully": "Signé \n Avec succès",
          "Create User": "Créer un utilisateur",
          "Checking E-mail": "Vérification du courrier électronique",
          "Not Valid Username": "Nom d'utilisateur non valide",
          "Not Valid Email": "E-mail non valide",
          "Not Valid Phone Number": "Numéro de téléphone non valide",
          "please fill the fields": "remplir les champs",
          "Can't be less than": "Ne peut pas être inférieur à",
          "Can't be larger than": "Ne peut pas être plus grand que",
          "Warning": "Avertissement",
          "Do You Want To Close The App": "Voulez-vous fermer l'application",
          "Confirm": "Confirmer",
          "Cancel": "Annuler",
          "Email or username already exist":
              "L'e-mail ou le nom d'utilisateur existent déjà",
          "Verify Code Not Correct": "Vérifier que le code n'est pas correct",
          "Email or password not correct": "Email ou mot de passe incorrect",
          "Email Not Found": "Email non trouvé",
          "Password Not Match": "le mot de passe ne correspond pas",
          "Try Again": "Essayer à nouveau",
          "search": "recherche",
          "Categories": "Catégories",
          "Top Services For You": "Top Services For You",
          "offer": "offer",
          "Rating": "Notation",
          "Home": "Maison",
          "Profile": "Profil",
          "Setting": "Paramètre",
          "Request": "Demande",
          "Edit Your Password": "Modifiez votre mot de passe",
          "Edit": "Modifier",
          "Edit Your Phone Number": "Modifier votre numéro de téléphone",
          "Edit Your User Name": "Modifier votre nom d'utilisateur",
          "Edit Your Zodiac": "Modifiez votre signe du zodiaque",
          "Add comment": "Ajouter un commentaire",
          "Write a Comment": "Écrire un commentaire ..",
          "Notification": "Notification",
          "Fill your information and your question":
              "Remplissez vos informations et votre question",
          "Enter Your Full Name": "Entrez votre nom complet",
          "Full Name": "Nom et prénom",
          "Enter Your Question": "Entrez votre question",
          "Question": "Question",
          "Choose Image": "Choisir une image",
          "Image Succefuly uploaded": "Image téléchargée avec succès",
          "Upload photo From Camera":
              "Télécharger une photo depuis l'appareil photo",
          "Upload photo From Gallery":
              "Télécharger une photo depuis la galerie",
          "Send": "Envoyer",
          "please fill all the info":
              "veuillez remplir toutes les informations",
          "Admin approved": "Approuvé par l'administrateur",
          "price": "prix",
          "Waiting For Answer": "Attendre une réponse",
          "Answer delevierd": "Réponse fournie",
          "Answer": "Répondre",
          "Add a rating": "Ajouter une note",
          "Technical Support": "Soutien technique",
          "Language": "Langue",
          "Contact Us": "Contactez-nous",
          "Log Out": "Se déconnecter",
          "Please enter your questions or problems you are having":
              "Veuillez entrer vos questions ou les problèmes que vous rencontrez",
          "Contact": "Contact",
          "Bio": "Biographie",
          "Favorite": "Préférée",
          "Rating Dialog": "Notation",
          "Tap a star to set your rating":
              "Appuyez sur une étoile pour définir votre note",
          "please insert an image": "veuillez insérer une image",
          "Your comment will succefulyy add":
              "Votre commentaire sera ajouté avec succès",
          "when admin approved it": "quand l'administrateur l'a approuvé",
          "Virgo": "Vierge",
          "Libra": "Balance",
          "Scorpion": "Scorpion",
          "Sagittarius": "Sagittaire",
          "Capricorn": "Capricorne",
          "Aquarius": "Verseau",
          "Pisces": "Poissons",
          "Aries": "Bélier",
          "Taurus": "Taureau",
          "Gemini": "Gémeaux",
          "Cancer": "Cancer",
          "Leo": "Leo",
          "Done": "Fait",
          "Edited Complete": "Edité terminé",
          "Pause": "Pause",
          "Play": "Jouer",
          "online": "en ligne",
          "offline": "hors ligne",
          "Rejected Request": "Demande rejetée",
          "Archive": "Archive",
          "Responses": "réponses",
          "Please enter your Credit Card":
              "Veuillez entrer votre carte de crédit",
          "Add": "ajouter",
          "Explore Your Insight": "Explorez votre vision",
        }
      };
}
